10th sprint done
FortovEgor/java-filmorate pull request #2
Opened 2024-09-15 14:56 UTC by FortovEgor

2024-09-16 08:31 UTC, EugeneLenkevich requested changes
Привет, Егор! Спасибо за PR.

По мелочи и для общего развития отметил несколько мест, которые можно причесать. Главное сделать так чтобы для классов-моделей equals и hashCode генерировался по id, это может быть потом критично, когда у нас появится БД 

Ну и сборочка красная, ее просят зеленой, но вроде мелочь, импорты лишние

![image](https://github.com/user-attachments/assets/0018332e-8874-4c23-8d18-d720c5abff93)

2024-09-23 19:54 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getName().isBlank()) {
сделано

2024-09-23 19:54 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private Map<Integer, User> users = new HashMap<>();
сделано

2024-09-23 19:56 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +public class ValidationException extends RuntimeException {
сделано

2024-09-23 20:41 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@Data
done

2024-09-23 21:19 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@Data
Евгений, не могу понять, почему не проходят автотесты

2024-09-24 08:22 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +@Data
> Евгений, не могу понять, почему не проходят автотесты

Ох, это лучше у наставника уточнить, он быстрее сориентирует, но что я вижу по логу - где то падает ошибка, потому эндпоинты возвращают 500-ую ошибку

Это после удаления `@Data`? Хотя вроде get- и set-методы на месте

В общем тут надо глубже копать, посмотреть что именно за ошибка.

2024-10-05 18:36 UTC, EugeneLenkevich requested changes
Привет, в первую очередь стоит допинать сборку, надо чтобы была зеленая, посмотри, пожалуйста :)

2024-10-06 03:48 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2024-11-03 11:27 UTC, merged