Add friends likes
FortovEgor/java-filmorate pull request #4
Opened 2024-11-04 18:23 UTC by FortovEgor

Спринт 11

2024-11-05 08:41 UTC, EugeneLenkevich requested changes
Привет, Егор! Спасибо за PR.

Пробегись, пожалуйста, по коду и посмотри везде ли правильно идет разделение логики по слоям.

 У каждого слоя есть свои обязанности, вот так
- контроллеры маршрутизируют сами запросы на наши сервисы
- сервисы оперируют понятиями предметной области, в них и содержится вся бизнес-логика 
- хранилище же занимается вопросами хранения, фильтрации и выборки данных

Но, в целом, все здорово :)

2024-11-05 08:41 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService, FilmStorage filmStorage, UserStorage userStorage) {
Можно использовать `@ReuiredArgsConstructor`, меньше бойлерплейт-кода, проще читать :)

2024-11-05 08:41 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!userStorage.getUsers().containsKey(userId)) {
По своей сути контроллер только обрабатывает (маршрутизирует сервисам) запросы, а тут же в контроллере выполняется некоторая бизнес-логика, ее лучше перенести в сервис, иначе логика размазывается по нескольким классам :)

2024-11-05 08:41 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!userStorage.getUsers().containsKey(userId)) {
Аналогично, логика в контроллере

2024-11-05 08:41 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (findFilmById(filmId).getIdUsersWhoLikedFilm().isEmpty()) {
Вот тут бы метод репозитория сделать, который будет проверять на существование записи

2024-11-05 08:41 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.findAll().isEmpty()) {
.findAll()

Допустим у нас потом будет СУБД и в табличке будут миллионы записей, то есть это место потенциальной ошибки. Тут стоит на уровне репозитория сделать такой метод, а тут уже вызывать его. Так мы, если надо будет, сможем изменить только один метод и не придется по всему коду выискивать

2024-11-05 08:41 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(Comparator.comparing(Film::getFilmsLikes).reversed())
И вот тут в сервис мы вытаскиваем все данные из хранилища и сортируем их

Вообще, выборка и сортировка - это обязанности хранилища, потому лучше опять таки спрятать это выражение в метод хранилища. Так же, потом, нам проще будет делать оптимизации хранения данных, прозрачно для сервисов

2024-11-05 08:41 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .filter(getUserFriends(friend)::contains)
Фильтрация - в репозиторий

2024-11-05 08:41 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        log.debug("Пользователь {} создан.", user.getLogin());
Это же описание бизнес логики, тут можно и log.info(...)

 В принципе какие то тут правил нет, но вот есть такое соображение

- error - нештатные ситуации
- warn - штатные ошибки, та же валидация
- info - бизнес операции, плюс сюда в лог стоит включать какие то базовые идентификаторы, по которым можно будет сопоставлять строки лога с конкретными сущностями
- debug - дополнительная техническая информация, можно содержимое dto распечатывать, например (в реальном приложении только с этим аккуратно, не стоит так раскрывать какую то конфиденциальную информацию)
- trace это совсем какие то мелочи логируются, может даже строчки кода, но нам не надо это особо 


log.info Обновление сущности, id=
log.debug dto= {}
log.info Сущность успешно создана

log.warn Ошибка валидации, значение {} недопустимо
log.error Нет соединения с БД

2024-11-05 15:07 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService, FilmStorage filmStorage, UserStorage userStorage) {
а тогда как на конструктор навесить @Autowired ?

2024-11-05 15:26 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.findAll().isEmpty()) {
согласен. O(1) лучше, нежели O(n) ))))

2024-11-05 18:09 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +                .sorted(Comparator.comparing(Film::getFilmsLikes).reversed())
done

2024-11-05 18:10 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!userStorage.getUsers().containsKey(userId)) {
Если один репозиторий зависит от другого - это норм. Но еще лучше если сервис зависит от двух репозиториев и вызывает их методы. Как то так еще лучше :)

2024-11-05 18:15 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (findFilmById(filmId).getIdUsersWhoLikedFilm().isEmpty()) {
Пусть исключение бросает сервис. То что репозиторий возвращает null - это нормально. Еще лучше, конечно, Optional.empty(), но это уже синтаксический сахар. 
Иначе мы логику прибиваем гвоздями бросая исключение в хранилище. Пусть сервис сам решает что делать с ситуацией когда фильм не найден иначе получается мы заносим часть бизнес-логики в хранилище. Тут на самом деле особых правил нет, скорее все на основе здравой логики.

2024-11-05 18:16 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (filmStorage.findAll().isEmpty()) {
Ну, да. Когда у нас будет БД это будут разные запросы, с кардинально разным потреблением ресурсов :)

2024-11-05 18:17 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +                .filter(getUserFriends(friend)::contains)
done

2024-11-05 18:18 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +        log.debug("Пользователь {} создан.", user.getLogin());
ок, понял, исправил.

2024-11-05 18:19 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService, FilmStorage filmStorage, UserStorage userStorage) {
А не надо навешивать, сервис сам определит что надо передать бины в конструктор (главное не оставлять конструктора без параметров, тогда спринг запутается)
`@Autowired` - это просто другой способ,  тогда и конструктора не надо, бины будут передаваться через соответствующие set-методы. То есть или так или так, два разных споосба

2024-11-08 21:55 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(FilmService filmService, FilmStorage filmStorage, UserStorage userStorage) {
понял

2024-11-08 22:15 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (findFilmById(filmId).getIdUsersWhoLikedFilm().isEmpty()) {
а что такое репозиторий?) это какой-то спец Spring репозитоий? есть какая-то статья почитать поподробнее?

2024-11-08 22:17 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!userStorage.getUsers().containsKey(userId)) {
done

2024-11-08 22:17 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (!userStorage.getUsers().containsKey(userId)) {
done

2024-11-09 05:58 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (findFilmById(filmId).getIdUsersWhoLikedFilm().isEmpty()) {
Ох, запутал только, имел в виду хранилище, конечно же, вообще, репозитори - это несколько другое и они, кстати, у нас потом появятся.
А вообще, это паттерн проектирования такой https://habr.com/ru/articles/263033/ но это все мы потом увидим, в спринге это есть :)

2024-11-09 09:50 UTC, FortovEgor commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        if (findFilmById(filmId).getIdUsersWhoLikedFilm().isEmpty()) {
done

2024-11-09 17:00 UTC, EugeneLenkevich requested changes
Большую работу проделал :)
Лучше везде соблюсти последовательность контроллер->сервис->хранилище. То есть только сервис пусть ходит в хранилище, даже если в методе сервиса остается только один вызов метода хранилища. Так структура приложения будет проще и более предсказуемой, с минимум лишних связей. И вижу ты перестарался малость сохранение объектов полностью в хранилища убрал, все проверки стоит поднять в сервис, хранилище у нас будет только лишь проксировать(добавлять/получать/удалять записи) мапу с данными  :)

2024-11-11 10:08 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2024-11-26 21:12 UTC, merged